version: 2
updates:
- package-ecosystem: gradle
  directory: "/07_crud/server"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - Onotole1
- package-ecosystem: gradle
  directory: "/08_coroutines/server"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - Onotole1
